import 'package:get/get.dart';

class AppLanguages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {
      'MN': 'My Notes',
      'S': 'sort',
      'LM': 'Light Mode',
      'DM': 'Dark Mode',
      'Se': 'Settings',
      'CL': 'Languages',
      'Clang': 'Choose Language',
      'OB': 'Order By :',
      'ASC': 'Ascending',
      'DESC': 'Descending',
      'AR': 'Arabic',
      'EN': 'English',
      'ET': 'Edit Theme',
      'FZ': 'Font Size',
      'H': 'Hello...',
      'C': 'Colors',
      'AB': 'App Bar',
      'BG': 'Background',
      'TB': 'Title And Buttons',
      'T': 'Text',
      'RT': 'Rest Theme',
      'Ti': 'Title',
      'AN': 'Add Note',
      'MO': 'More options',
      'RO': 'Please rotate your phone',
      'A': 'About',
      'D': 'This app developed by Mohammed Al-batol,\nit is a useful tool for organizing and keeping track of notes and information. With this app, users can easily create, edit, and organize notes on their mobile devices.'
    },
    'ar': {
      'MN': 'ملاحظاتي',
      'S': 'فرز',
      'LM': 'الوضع النهاري',
      'DM': 'الوضع الليلي',
      'Se': 'الاعدادات',
      'CL': 'اللغات',
      'Clang': 'اختر اللغة',
      'OB': 'ترتيب :',
      'ASC': 'تصاعدي',
      'DESC': 'تنازلي',
      'AR': 'العربية',
      'EN': 'الانجليزية',
      'ET': 'تعديل الثيم',
      'FZ': 'حجم الخط',
      'H': 'مرحبّّا',
      'C': 'الألوان',
      'AB': 'البار العلوي',
      'BG': 'الخلفية',
      'TB': 'العنوان والأزرار',
      'T': 'النص',
      'RT': ' تهيئة الثيم',
      'Ti': 'العنوان',
      'AN': 'اضافة ملاحظة',
      'MO': 'خيارات',
      'RO': 'من فضلك قم بتدوير الهاتف',
      'A': 'حول',
      'D': 'تم تطوير هذا التطبيق بواسطة محمد البتول',
    },
  };

}